namespace RR.Data.DataBaseObjects;

[Tables(nameof(ReceiptDBO))]
public class ReceiptDBO : AbstractPublicOwnable
{ 
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }
    public bool IsAutoGenerated { get; set; } = false;
    public int VendorId { get; set; }
    public virtual VendorDBO Vendor { get; set; }
    public virtual List<ReceiptItemDBO> Items { get; set; }
    [NotMapped]
    public double TotalFromItems => Items.Sum(i => i.Price);
    public double? Total {  get; set; }
    public DateTime? TransactionDateTime { get; set; }
    public int? ImageId { get; set; }
    public virtual ImageDBO? Image { get; set; }

    public static implicit operator Receipt(ReceiptDBO receiptDBO) => new()
    {
        Id = receiptDBO.Id,
        GroupId = receiptDBO.GroupId,
        Vendor = receiptDBO.Vendor,
        Items = [.. receiptDBO.Items.Select(i => (ReceiptItem)i)],
        TransactionDateTime = receiptDBO.TransactionDateTime,
    };
}
