namespace RR.Service.Services;

public class ReceiptService(
    IDocumentIntelligenceService documentIntelligenceService,
    IReceiptRepository receiptRepository,
    IReceiptItemRepository receiptItemRepository,
    IGroupRepository groupRepository,
    IImageService imageService,
    ISecurityService securityService,
    IVendorRepository vendorRepository,
    ILanguageRespository languageRespository
) : IReceiptService
{
    public async Task<Receipt> CreateReceiptAsync(Receipt receipt, UserDBO? userDBO = null, bool isAutoGenerated = false)
    {
        if (receipt.Id is not null)
            throw new BadRequestException("Receipt to be created cannot already have an Id.");
        userDBO ??= await securityService.GetUserAsync();
        var userGroup = await groupRepository.EnsureCanEditOwn(userDBO.ShortId, receipt.GroupId);
        var language = await languageRespository.GetLanguageForUserAsync(receipt.Language, userDBO);
        var vendorDBO = await vendorRepository.GetOrCreateVendorAsync(new VendorDBO(receipt.Vendor, userDBO.ShortId));
        var newReceipt = new ReceiptDBO
        {
            IsAutoGenerated = isAutoGenerated,
            UserShortId = userDBO.ShortId,
            GroupId = userGroup?.GroupId,
            VendorId = vendorDBO.Id,
            Items = await receiptItemRepository.PreProcessReceiptItemsAsync(receipt.Items, language.Id, userDBO, userGroup?.GroupId),
            TransactionDateTime = receipt.TransactionDateTime,
        };
        newReceipt = await receiptRepository.CreateReceipt(newReceipt);
        return newReceipt;
    }

    public async Task<Receipt> CreateReceiptFromImageAsync(string imageName, int? imageId, int? groupId)
    {
        var userDBO = await securityService.GetUserAsync();

        var imageURI = await imageService.GetImageURI(imageName, imageId, userDBO.ShortId);
        var receipt = await documentIntelligenceService.ExtractReceiptDataFromImageAsync(imageURI, groupId);
        return await CreateReceiptAsync(receipt, userDBO, isAutoGenerated: true);
    }
    public async Task<Receipt> CreateReceiptFromImageAsync(bool isImagePublic, bool isReceiptPublicbool, int? groupId, IFormFile image)
    {
        var userDBO = await securityService.GetUserAsync();

        var uri =  await imageService.CreateImageAndGetURIAsync(image, isImagePublic, groupId);
        var language = await languageRespository.GetLanguageForUserAsync(languageCode, userDBO);
        var receipt = await documentIntelligenceService.ExtractReceiptDataFromImageAsync(uri, groupId);
        return await CreateReceiptAsync(receipt, userDBO, isAutoGenerated: true);
    }

    public async Task<ReceiptValidated> ValidateReceipt(ReceiptDBO receiptDBO)
    {
        var result = (ReceiptValidated)receiptDBO;
        var vendor = await vendorRepository.ValidateVendor(receiptDBO.Vendor);
        result.Vendor = vendor;
        var items = await receiptItemRepository.ValidateItems(receiptDBO.Items);
        result.Items = items;
        
        if (receiptDBO.TransactionDateTime is null)
            result.ValidationMessages.CreateAdd(nameof(result.TransactionDateTime), $"e:Transaction Time must be present");
        return result;
    }
}

public static class DictionaryExtensions
{
    public static bool CreateAdd(this Dictionary<string, string>? dictionary, string key, string value)
    {
        dictionary ??= [];
        return dictionary.TryAdd(key, value);
    }
}
