using Microsoft.AspNetCore.Mvc;

namespace RR.Service.Interfaces;

public interface IReceiptService
{
    Task<Receipt> CreateReceiptAsync(Receipt receipt, UserDBO? user = null, bool isAutoGenerated = false);
    Task<Receipt> CreateReceiptFromImageAsync(string imageName, int? imageId, int? groupId);
    Task<Receipt> CreateReceiptFromImageAsync(bool isImagePublic, bool isReceiptPublicbool, int? groupId, IFormFile image);
}
