global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.IdentityModel.Tokens;
global using RR.API;
global using RR.API.Configuration;
global using RR.Common.IntermediateModels;
global using RR.Common.Models;
global using RR.Configuration;
global using RR.Data;
global using RR.Data.DataBaseObjects;
global using RR.Data.Interfaces;
global using RR.Service.Interfaces;
global using System.ComponentModel.DataAnnotations;
global using System.Text;
global using System.Text.Json.Serialization;

